### PR TITLE
Sys

### PR DESCRIPTION
**Pull request by scopatz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Trying to follow the instructions here: https://github.com/conda-forge/cfep/issues/17#issuecomment-579903153

It wasn't clear that the activation script was needed.  Maybe the same could be accomplished via a run constraint

### CODE REVIEW

**Comment by isuruf** [comment]
We are only using this package for osx and there's no point in having a system only package. Try `ocl-icd-feedstock`.

**Comment by scopatz** [comment]
Hey @isuruf - the whole point of this was for OSX. I don't think this should be closed on that grounds.

**Comment by scopatz** [comment]
Or are you trying to say that this implementation has been moved to ocl-icd-feedstock?

**Comment by isuruf** [comment]
On OSX, by default there's no ICD loader. Only Apple's OpenCL implementation. If you only want that, you should link against that directly instead of going through an ICD loader. This ICD loader will not see Apple's OpenCL implementation without `$PREFIX/etc/OpenCL/vendors/apple.icd`

**Comment by scopatz** [comment]
So are you saying that I should add the system-only variant to `ocl-icd-feedstock` then?  Between what you said at  https://github.com/conda-forge/cfep/issues/17#issuecomment-579903153 and what you are saying here, I am confused on how to get the system-only loader for Mac

**Comment by scopatz** [comment]
I am happy to put in the effort wherever it is. I think I just need clarity on what is going on.

**Pull request closed without merging**
